
CREATE TABLE `peliculas` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	`anio_estreno` INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


